version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
# back app
  back-app:
    image: iskander20/devopsproject:backapp
    container_name: spring-back-project
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devops-db:3306/devops_project_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - my-network
    volumes:
      - ./backend-data:/app/data  # Shared volume for the backend
## front app
  front-app:
    image: iskander20/devopsproject:frontapp
    container_name: angular-front-project
    ports:
      - "80:4200"
    depends_on:
      - back-app
    networks:
      - my-network
    volumes:
      - ./frontend-data:/app/dist  # Shared volume for the frontend
## network and shared volumes
networks:
  my-network:
