version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network

  back-app:
    image: iskander20/devopsproject:backapp
    container_name: spring-back-project
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devops-db:3306/devops_project_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: examplepassword
    networks:
      - my-network
    volumes:
      - ./backend-data:/app/data

  front-app:
    image: iskander20/devopsproject:frontapp
    container_name: angular-front-project
    ports:
      - "4200:4200"
    depends_on:
      - back-app
    networks:
      - my-network
    volumes:
      - ./frontend-data:/app/dist

networks:
  my-network:
